# Generated by Django 4.2.2 on 2023-07-21 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_imgor_game_mane_imgor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 20, 8, 10, 178308), verbose_name='дата истечения'),
        ),
    ]
