# Generated by Django 4.2.2 on 2023-07-21 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='mane_imgor',
            new_name='main_imgor',
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 20, 30, 58, 829969), verbose_name='дата истечения'),
        ),
    ]
